variables:
  IMAGE_NAME: moiznasir/moiz
  IMAGE_TAG: react-app-1.0

stages:
  - test
  - build
  - deploy

run_test:
  stage: test
  image: node:16-alpine
  before_script:
    - npm install
  script:
    - npm test

build_image:
  stage: build
  image: docker:26.1.4
  services:
    - docker:26.1.4-dind
  variables:
    DOCKER_TLS_CERTDIR: "/certs"

  before_script:
    - docker login -u $REG_USER -p $REG_PASS

  script:
    - docker build -t $IMAGE_NAME:$IMAGE_TAG .
    - docker push $IMAGE_NAME:$IMAGE_TAG
    
deploy:
  stage: deploy
  image: node:16-alpine
  before_script:
    - npm install -g vercel
  script:
    - vercel --token LpgDuJJ9dQiaPmXFTD9WgtDb --prod --yes
    