run_test:
    image: node:16-alpine
    before_script:
        - npm install
    script:
        - npm test

build_image:
    image: docker:20.10.16
    services:
        - docker:20.10.16-dind
    variables:
        DOCKER_TLS_CERTDIR: "/certs"
        IMAGE_NAME: moiznasir/moiz
        IMAGE_TAG: react-app-1.0
    before_script:
        - echo "$REG_PASS" | docker login -u "$REG_USER" --password-stdin


    script:
        - docker build -t $IMAGE_NAME:$IMAGE_TAG .
        - docker push $IMAGE_NAME:$IMAGE_TAG
        