env:
  IMAGE_NAME: moiznasir/moiz
  IMAGE_TAG: react-app-1.0 

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
     
jobs:
  test:
    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16'

      - run: npm install
      - run: npm test

  build:
  
    runs-on: ubuntu-latest
    needs: test

    steps:

      - uses: actions/checkout@v2
      - uses: docker/login-action@v2
        with:
          username: ${{ secrets.REG_USER }}
          password: ${{ secrets.REG_PASS }}
 
      - run: |
          if [ -n "$(docker ps -aq)" ]; then
            docker ps -aq | xargs docker stop
            docker ps -aq | xargs docker rm
          fi

      - run: |
            docker build -t $IMAGE_NAME:$IMAGE_TAG .
            docker push $IMAGE_NAME:$IMAGE_TAG

  deploy:

    runs-on: ubuntu-latest
    needs: build

    steps:
      - uses: actions/checkout@v2 
      - uses: actions/setup-node@v2
        with:
          node-version: '16'

      - run: npm install -g vercel
 
      - env:
          VERCEL_TOKEN: ${{ secrets.REG_VERCEL }}
        run: vercel --token ${{ secrets.REG_VERCEL }} --prod --yes